/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FullCTest */

#ifndef _Included_FullCTest
#define _Included_FullCTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FullCTest
 * Method:    run
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_FullCTest_run
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
