/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestingJNI */

#ifndef _Included_TestingJNI
#define _Included_TestingJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestingJNI
 * Method:    ioctl
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_TestingJNI_ioctl
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     TestingJNI
 * Method:    socket
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_TestingJNI_socket
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
